---
- name: Register required variables for yum
  set_fact:
    "{{ ansible_pkg_mgr }}_packages":
      - git
      - "@Development tools"
  when: ansible_pkg_mgr == "yum" or ansible_pkg_mgr == "dnf"

- name: Register packages for APT
  set_fact:
    "{{ ansible_pkg_mgr }}_packages":
      - git
      - build-essential
  when: ansible_pkg_mgr == "apt"

- name: Ensure required packages are installed
  include_role:
    name: frite.recon_package_manager

- name: Download latest source from GitHub  # noqa 401
  git:
    repo: https://github.com/blechschmidt/massdns.git
    dest: /usr/local/src/massdns/

- name: Build massdns
  make:
    chdir: /usr/local/src/massdns/
  changed_when: false

- name: Install massdns
  make:
    chdir: /usr/local/src/massdns/
    target: install
  changed_when: false
